services:
  - type: web
    name: allento1124.github.io
    runtime: python
    repo: https://github.com/allento124/allento1124.github.io
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    postDeployCommand: bash scripts/sync_databases.sh
version: "1"

